'use strict';
const API='https://api.tcgdex.net/v2/en';
const SUPABASE_URL='https://lretqhaattgtwpfwsxbc.supabase.co';
const SUPABASE_KEY='sb_publishable_6ntpA39F6O2fbB8wavLzoA_acDIJfrm';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null, currentCard=null, stream=null, installPrompt=null, items=[];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=(n,c='USD')=>n==null||Number.isNaN(Number(n))?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(n));
const imageUrl=(base,q='low')=>base?base+'/'+q+'.webp':'';
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800);}
function setAuthMessage(m,bad=false){const e=$('#authMessage');e.textContent=m||'';e.classList.toggle('error',bad);}
function showPane(id){['signinPane','signupPane','applicationPane','resetPane'].forEach(x=>{const e=$('#'+x);if(e)e.classList.toggle('hidden',x!==id);});setAuthMessage('');}
function showAuth(){currentUser=null;$('#authGate').classList.remove('hidden');$('#appShell').classList.add('hidden');}
async function showApp(user){
  const {data:approved,error:approvalError}=await sb.from('approved_users').select('user_id').eq('user_id',user.id).maybeSingle();
  if(approvalError||!approved){
    await sb.auth.signOut();
    showAuth();
    setAuthMessage('This account has not been approved for DeckVault yet.',true);
    return false;
  }
  currentUser=user;
  $('#authGate').classList.add('hidden');
  $('#appShell').classList.remove('hidden');
  $('#accountChip').textContent=user.email||'Signed in';
  $('#accountEmail').textContent=user.email||'';
  await loadCollection();renderDashboard();renderLibrary();
  return true;
}
async function loadCollection(){
  if(!currentUser){items=[];return;}
  const {data,error}=await sb.from('collection_items').select('*').order('added_at',{ascending:false});
  if(error){console.error(error);toast('Could not load collection');return;}
  items=(data||[]).map(fromRow);
}
function fromRow(r){return {id:r.id,game:r.game,cardId:r.card_id,name:r.name,localId:r.local_id,setId:r.set_id,setName:r.set_name,rarity:r.rarity,variant:r.variant,condition:r.condition,language:r.language,quantity:r.quantity,image:r.image_url,price:r.price==null?null:Number(r.price),priceCurrency:r.price_currency,priceSource:r.price_source,priceUpdatedAt:r.price_updated_at,notes:r.notes||'',addedAt:r.added_at,updatedAt:r.updated_at};}
function toRow(x){return {user_id:currentUser.id,game:x.game,card_id:x.cardId,name:x.name,local_id:x.localId,set_id:x.setId,set_name:x.setName,rarity:x.rarity,variant:x.variant,condition:x.condition,language:x.language,quantity:x.quantity,image_url:x.image,price:x.price,price_currency:x.priceCurrency,price_source:x.priceSource,price_updated_at:x.priceUpdatedAt,notes:x.notes||'',updated_at:new Date().toISOString()};}
async function signIn(e){e.preventDefault();setAuthMessage('Signing in…');const {data,error}=await sb.auth.signInWithPassword({email:$('#signInEmail').value.trim(),password:$('#signInPassword').value});if(error)return setAuthMessage(error.message,true);await showApp(data.user);}
async function signUp(e){e.preventDefault();showPane('applicationPane');setAuthMessage('New DeckVault accounts require administrator approval.');}
async function resetPassword(e){e.preventDefault();setAuthMessage('Sending recovery email…');const {error}=await sb.auth.resetPasswordForEmail($('#resetEmail').value.trim(),{redirectTo:location.origin+location.pathname});if(error)return setAuthMessage(error.message,true);setAuthMessage('Recovery email sent.');}
async function signOut(){await sb.auth.signOut();items=[];showAuth();}

function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.bottomnav button').forEach(b=>b.classList.toggle('active',b.dataset.go===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='dashboard')renderDashboard();if(view==='library')renderLibrary();}
async function pokemonSearch(name,number){const p=new URLSearchParams();if(name)p.set('name',name.trim());if(number)p.set('localId',number.trim());const r=await fetch(API+'/cards?'+p);if(!r.ok)throw new Error('TCGdex search failed ('+r.status+')');return r.json();}
async function pokemonCard(id){const r=await fetch(API+'/cards/'+encodeURIComponent(id));if(!r.ok)throw new Error('Could not load card');return r.json();}
function pokemonVariants(c){const v=c.variants||{},o=[];if(v.normal)o.push('Normal');if(v.holo)o.push('Holofoil');if(v.reverse)o.push('Reverse Holofoil');if(v.firstEdition)o.push('1st Edition');if(v.firstEdition&&v.holo)o.push('1st Edition Holofoil');return o.length?[...new Set(o)]:['Normal'];}
function variantPriceObject(tcg,v){if(!tcg)return null;const m={'Normal':['normal','unlimited'],'Holofoil':['holofoil','holo','unlimited-holofoil'],'Reverse Holofoil':['reverse-holofoil','reverse'],'1st Edition':['1st-edition','first-edition','firstEdition'],'1st Edition Holofoil':['1st-edition-holofoil','first-edition-holofoil']};for(const k of (m[v]||['normal']))if(tcg[k])return tcg[k];return null;}
function pricePref(){return localStorage.getItem('deckvault-price-source')||'tcgplayer-market';}
function pokemonPrice(c,v,s=pricePref()){const p=c.pricing||{};if(s.startsWith('tcgplayer')){const o=variantPriceObject(p.tcgplayer,v);return {value:s==='tcgplayer-mid'?(o&&o.midPrice):(o&&o.marketPrice),currency:(p.tcgplayer&&p.tcgplayer.unit)||'USD',label:s==='tcgplayer-mid'?'TCGplayer Mid':'TCGplayer Market'};}const cm=p.cardmarket||{},foil=v.toLowerCase().includes('holo'),k=s==='cardmarket-7'?(foil?'avg7-holo':'avg7'):(foil?'avg30-holo':'avg30');return {value:cm[k],currency:cm.unit||'EUR',label:s==='cardmarket-7'?'Cardmarket 7-day':'Cardmarket 30-day'};}
async function search(){const n=$('#searchName').value.trim(),no=$('#searchNumber').value.trim();if(!n&&!no)return toast('Enter a name or collector number');$('#searchStatus').textContent='Searching TCGdex…';try{const cards=await pokemonSearch(n,no);$('#searchStatus').textContent=cards.length+' match'+(cards.length===1?'':'es')+' found';renderResults(cards);}catch(e){$('#searchStatus').textContent=e.message;}}
function renderResults(cards){const b=$('#results');b.innerHTML='';if(!cards.length){b.innerHTML='<div class="empty">No matching cards found.</div>';return;}cards.slice(0,60).forEach(c=>{const e=document.createElement('article');e.className='result';e.innerHTML='<img loading="lazy" src="'+esc(imageUrl(c.image))+'" alt="'+esc(c.name)+'"><div class="info"><strong>'+esc(c.name)+'</strong><div class="meta">#'+esc(c.localId)+' • '+esc(c.id)+'</div><button>View / Add</button></div>';e.querySelector('button').onclick=()=>openCard(c.id);b.appendChild(e);});}
async function openCard(id){$('#dialogBody').innerHTML='<div class="empty">Loading card…</div>';$('#cardDialog').showModal();try{currentCard=await pokemonCard(id);const variants=pokemonVariants(currentCard),p=pokemonPrice(currentCard,variants[0]);$('#dialogBody').innerHTML='<div class="dialogtop"><img src="'+esc(imageUrl(currentCard.image,'high'))+'"><div><div class="eyebrow">'+esc(currentCard.set?.name||'Pokémon TCG')+'</div><h2>'+esc(currentCard.name)+'</h2><div class="muted">#'+esc(currentCard.localId)+(currentCard.rarity?' • '+esc(currentCard.rarity):'')+'</div><div class="pricebox"><div id="dialogPriceLabel" class="muted">'+esc(p.label)+'</div><div id="dialogPrice" class="pricebig">'+money(p.value,p.currency)+'</div></div></div></div><div class="fields"><label>Variant<select id="variant">'+variants.map(v=>'<option>'+esc(v)+'</option>').join('')+'</select></label><label>Condition<select id="condition"><option>Near Mint</option><option>Lightly Played</option><option>Moderately Played</option><option>Heavily Played</option><option>Damaged</option></select></label><label>Language<select id="language"><option>English</option><option>Japanese</option><option>French</option><option>German</option><option>Italian</option><option>Spanish</option></select></label><label>Quantity<input id="qty" type="number" min="1" value="1"></label></div><div class="dialogactions"><button id="addCard" type="button" class="primary">Add to collection</button><button class="secondary" value="cancel">Cancel</button></div>';$('#variant').onchange=()=>{const q=pokemonPrice(currentCard,$('#variant').value);$('#dialogPrice').textContent=money(q.value,q.currency);$('#dialogPriceLabel').textContent=q.label;};$('#addCard').onclick=addCurrent;}catch(e){$('#dialogBody').innerHTML='<div class="empty">'+esc(e.message)+'</div>';}}
async function addCurrent(){const variant=$('#variant').value,condition=$('#condition').value,language=$('#language').value,qty=Math.max(1,parseInt($('#qty').value||'1',10)),p=pokemonPrice(currentCard,variant),old=items.find(x=>x.game==='pokemon'&&x.cardId===currentCard.id&&x.variant===variant&&x.condition===condition&&x.language===language),now=new Date().toISOString();const x={game:'pokemon',cardId:currentCard.id,name:currentCard.name,localId:String(currentCard.localId),setId:currentCard.set?.id||'',setName:currentCard.set?.name||'',rarity:currentCard.rarity||'',variant,condition,language,quantity:(old?old.quantity:0)+qty,image:currentCard.image||'',price:p.value==null?null:Number(p.value),priceCurrency:p.currency,priceSource:p.label,priceUpdatedAt:now,notes:old?.notes||'',addedAt:old?.addedAt||now};let q;if(old)q=await sb.from('collection_items').update(toRow(x)).eq('id',old.id).select().single();else q=await sb.from('collection_items').insert({...toRow(x),added_at:now}).select().single();if(q.error)return toast('Could not save card');$('#cardDialog').close();await loadCollection();renderDashboard();toast(currentCard.name+' saved');}
function rowFor(x,compact){const e=document.createElement('div');e.className='cardrow';const total=(Number(x.price)||0)*(Number(x.quantity)||0);e.innerHTML='<img loading="lazy" src="'+esc(imageUrl(x.image))+'"><div class="cardmain"><div class="cardtitle">'+esc(x.name)+'</div><div class="cardmeta">'+esc(x.setName)+' • #'+esc(x.localId)+' • '+esc(x.variant)+' • '+esc(x.condition)+'</div>'+(compact?'':'<div class="qty"><button data-a="dec">−</button><span>'+x.quantity+'</span><button data-a="inc">+</button><button data-a="del">×</button></div>')+'</div><div class="cardprice">'+money(total,x.priceCurrency||'USD')+'<div class="cardmeta">×'+x.quantity+'</div></div>';if(!compact){e.querySelector('[data-a="inc"]').onclick=()=>adjust(x,1);e.querySelector('[data-a="dec"]').onclick=()=>adjust(x,-1);e.querySelector('[data-a="del"]').onclick=()=>removeEntry(x);}return e;}
async function adjust(x,d){const q=x.quantity+d;if(q<=0)return removeEntry(x);const {error}=await sb.from('collection_items').update({quantity:q,updated_at:new Date().toISOString()}).eq('id',x.id);if(error)return toast('Could not update quantity');await loadCollection();renderLibrary();renderDashboard();}
async function removeEntry(x){if(!confirm('Remove '+x.name+' from this collection?'))return;const {error}=await sb.from('collection_items').delete().eq('id',x.id);if(error)return toast('Could not remove card');await loadCollection();renderLibrary();renderDashboard();}
function renderDashboard(){const count=items.reduce((s,x)=>s+Number(x.quantity||0),0),total=items.reduce((s,x)=>s+((x.priceCurrency==='USD'||!x.priceCurrency)?Number(x.price||0)*Number(x.quantity||0):0),0);$('#collectionValue').textContent=money(total);$('#totalCards').textContent=count.toLocaleString();$('#uniqueCards').textContent=items.length.toLocaleString();$('#duplicates').textContent=Math.max(0,count-items.length).toLocaleString();$('#setCount').textContent=new Set(items.map(x=>x.game+':'+x.setId).filter(Boolean)).size.toLocaleString();const r=[...items].sort((a,b)=>new Date(b.addedAt)-new Date(a.addedAt)).slice(0,5),b=$('#recent');b.innerHTML='';if(!r.length){b.className='panel empty';b.textContent='No cards yet.';}else{b.className='panel';r.forEach(x=>b.appendChild(rowFor(x,true)));}}
function renderLibrary(){let a=[...items],q=$('#librarySearch').value.trim().toLowerCase(),s=$('#librarySort').value;if(q)a=a.filter(x=>[x.name,x.setName,x.localId,x.variant,x.condition].some(v=>String(v||'').toLowerCase().includes(q)));a.sort((x,y)=>s==='name'?x.name.localeCompare(y.name):s==='set'?(x.setName||'').localeCompare(y.setName||'')||x.name.localeCompare(y.name):s==='value'?Number(y.price||0)*y.quantity-Number(x.price||0)*x.quantity:s==='quantity'?y.quantity-x.quantity:new Date(y.addedAt)-new Date(x.addedAt));const b=$('#libraryList');b.innerHTML='';if(!a.length)b.innerHTML='<div class="empty">No cards match this view.</div>';else a.forEach(x=>b.appendChild(rowFor(x,false)));}
async function refreshPrices(){if(!items.length)return toast('No cards to refresh');const btn=$('#refreshPrices');btn.disabled=true;btn.textContent='Refreshing…';for(const id of [...new Set(items.filter(x=>x.game==='pokemon').map(x=>x.cardId))].slice(0,50)){try{const c=await pokemonCard(id);for(const x of items.filter(i=>i.cardId===id)){const p=pokemonPrice(c,x.variant);await sb.from('collection_items').update({price:p.value==null?null:Number(p.value),price_currency:p.currency,price_source:p.label,price_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',x.id);}}catch(e){console.warn(e);}}await loadCollection();btn.disabled=false;btn.textContent='Refresh prices';renderLibrary();renderDashboard();toast('Prices refreshed');}
async function startCamera(){try{if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});$('#video').srcObject=stream;$('#cameraPlaceholder').classList.add('hidden');$('#video').classList.remove('hidden');$('#capturePreview').classList.add('hidden');$('#captureCard').disabled=false;$('#cameraStatus').textContent='Camera ready';}catch(e){$('#cameraStatus').textContent='Camera blocked';alert('Camera access failed. '+e.message);}}
function capture(){const v=$('#video');if(!v.videoWidth)return;const c=$('#canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);$('#capturePreview').src=c.toDataURL('image/jpeg',.9);$('#capturePreview').classList.remove('hidden');v.classList.add('hidden');$('#captureCard').classList.add('hidden');$('#retake').classList.remove('hidden');$('#cameraStatus').textContent='Captured';}
function retake(){$('#capturePreview').classList.add('hidden');$('#video').classList.remove('hidden');$('#captureCard').classList.remove('hidden');$('#retake').classList.add('hidden');$('#cameraStatus').textContent='Camera ready';}
function download(content,type,name){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csv=v=>{const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;};
async function exportJson(){download(JSON.stringify({format:'deckvault-backup',version:2,exportedAt:new Date().toISOString(),collection:items},null,2),'application/json','deckvault-backup-'+new Date().toISOString().slice(0,10)+'.json');}
async function exportCsv(collectr){const cols=collectr?['Game','Card Name','Set','Card Number','Variant','Condition','Language','Quantity','Provider ID','Current Price','Currency']:['Game','Name','Set','Set ID','Card Number','Variant','Condition','Language','Quantity','Rarity','Provider ID','Price','Currency','Price Source','Added At','Updated At','Notes'];const rows=items.map(x=>collectr?[x.game,x.name,x.setName,x.localId,x.variant,x.condition,x.language,x.quantity,x.cardId,x.price||'',x.priceCurrency||'']:[x.game,x.name,x.setName,x.setId,x.localId,x.variant,x.condition,x.language,x.quantity,x.rarity,x.cardId,x.price||'',x.priceCurrency||'',x.priceSource||'',x.addedAt,x.updatedAt,x.notes||'']);download([cols,...rows].map(r=>r.map(csv).join(',')).join('\n'),'text/csv;charset=utf-8',(collectr?'deckvault-collectr-transfer-':'deckvault-collection-')+new Date().toISOString().slice(0,10)+'.csv');}
async function importBackup(file){const d=JSON.parse(await file.text());if(!d||!Array.isArray(d.collection))throw new Error('Not a valid DeckVault backup.');if(!confirm('Restore '+d.collection.length+' entries to this account?'))return;for(const x of d.collection){const cardId=x.cardId||x.card_id;if(!cardId)continue;const variant=x.variant||'Normal',condition=x.condition||'Near Mint',language=x.language||'English';const old=items.find(i=>i.game===(x.game||'pokemon')&&i.cardId===cardId&&i.variant===variant&&i.condition===condition&&i.language===language);const obj={game:x.game||'pokemon',cardId,name:x.name||'',localId:x.localId||x.local_id||'',setId:x.setId||x.set_id||'',setName:x.setName||x.set_name||'',rarity:x.rarity||'',variant,condition,language,quantity:Number(x.quantity||1),image:x.image||x.image_url||'',price:x.price==null?null:Number(x.price),priceCurrency:x.priceCurrency||x.price_currency||'USD',priceSource:x.priceSource||x.price_source||'',priceUpdatedAt:x.priceUpdatedAt||x.price_updated_at||null,notes:x.notes||'',addedAt:x.addedAt||x.added_at||new Date().toISOString()};if(old)await sb.from('collection_items').update(toRow({...obj,id:old.id})).eq('id',old.id);else await sb.from('collection_items').insert({...toRow(obj),added_at:obj.addedAt});}await loadCollection();renderDashboard();renderLibrary();toast('Backup restored');}

async function init(){
  $$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
  $('#signInForm').onsubmit=signIn;$('#signUpForm').onsubmit=signUp;$('#resetForm').onsubmit=resetPassword;
  $('#showSignUp').onclick=()=>showPane('applicationPane');$('#showSignIn').onclick=()=>showPane('signinPane');$('#showReset').onclick=()=>showPane('resetPane');$('#resetBack').onclick=()=>showPane('signinPane');
  $('#signOutBtn').onclick=signOut;$('#searchBtn').onclick=search;$('#searchName').onkeydown=e=>{if(e.key==='Enter')search();};$('#searchNumber').onkeydown=e=>{if(e.key==='Enter')search();};
  $('#librarySearch').oninput=renderLibrary;$('#librarySort').onchange=renderLibrary;$('#refreshPrices').onclick=refreshPrices;$('#startCamera').onclick=startCamera;$('#captureCard').onclick=capture;$('#retake').onclick=retake;
  $('#exportJson').onclick=exportJson;$('#exportCsv').onclick=()=>exportCsv(false);$('#exportCollectr').onclick=()=>exportCsv(true);$('#importJson').onchange=async e=>{if(e.target.files[0])try{await importBackup(e.target.files[0]);}catch(err){alert(err.message);}e.target.value='';};
  $('#clearData').onclick=async()=>{if(confirm('Delete every card in your DeckVault account collection?')){const {error}=await sb.from('collection_items').delete().eq('user_id',currentUser.id);if(error)return toast('Could not clear collection');await loadCollection();renderDashboard();renderLibrary();toast('Collection cleared');}};
  $('#priceSource').value=pricePref();$('#priceSource').onchange=e=>{localStorage.setItem('deckvault-price-source',e.target.value);toast('Price source saved');};
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').classList.add('hidden');};
  sb.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_OUT')showAuth();else if(session?.user&&!currentUser)await showApp(session.user);});
  const {data:{session}}=await sb.auth.getSession();if(session?.user)await showApp(session.user);else showAuth();
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
}
document.addEventListener('DOMContentLoaded',init);
window.addEventListener('pagehide',()=>{if(stream)stream.getTracks().forEach(t=>t.stop());});